CREATE TABLE COURSE 
(
  COURSE_NO NUMBER(8, 0) NOT NULL 
, DESCRIPTION VARCHAR2(50 BYTE) NOT NULL 
, COST NUMBER(9, 2) 
, PREREQUISITE NUMBER(8, 0) 
, CREATED_BY VARCHAR2(30 BYTE) NOT NULL 
, CREATED_DATE DATE NOT NULL 
, MODIFIED_BY VARCHAR2(30 BYTE) NOT NULL 
, MODIFIED_DATE DATE NOT NULL 
, CONSTRAINT COURSE_PK PRIMARY KEY 
  (
    COURSE_NO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COURSE_PK ON COURSE (COURSE_NO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE COURSE
ADD CONSTRAINT COURSE_FK1 FOREIGN KEY
(
  PREREQUISITE 
)
REFERENCES COURSE
(
  COURSE_NO 
)
ENABLE;


CREATE TABLE ENROLLMENT 
(
  STUDENT_ID NUMBER(8, 0) NOT NULL 
, SECTION_ID NUMBER(8, 0) NOT NULL 
, ENROLL_DATE DATE NOT NULL 
, FINAL_GRADE NUMBER(3, 0) 
, CREATED_BY VARCHAR2(30 BYTE) NOT NULL 
, CREATED_DATE DATE NOT NULL 
, MODIFIED_BY VARCHAR2(30 BYTE) NOT NULL 
, MODIFIED_DATE DATE NOT NULL 
, CONSTRAINT ENROLLMENT_PK PRIMARY KEY 
  (
    STUDENT_ID 
  , SECTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ENROLLMENT_PK ON ENROLLMENT (STUDENT_ID ASC, SECTION_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE ENROLLMENT
ADD CONSTRAINT ENROLLMENT_FK1 FOREIGN KEY
(
  SECTION_ID 
)
REFERENCES SECTION
(
  SECTION_ID 
)
ENABLE;

ALTER TABLE ENROLLMENT
ADD CONSTRAINT ENROLLMENT_FK2 FOREIGN KEY
(
  STUDENT_ID 
)
REFERENCES STUDENT
(
  STUDENT_ID 
)
ENABLE;


CREATE TABLE SECTION 
(
  SECTION_ID NUMBER(8, 0) NOT NULL 
, COURSE_NO NUMBER(8, 0) NOT NULL 
, SECTION_NO NUMBER(3, 0) NOT NULL 
, START_DATE_TIME DATE 
, LOCATION VARCHAR2(50 BYTE) 
, INSTRUCTOR_ID NUMBER(8, 0) NOT NULL 
, CAPACITY NUMBER(3, 0) 
, CREATED_BY VARCHAR2(30 BYTE) NOT NULL 
, CREATED_DATE DATE NOT NULL 
, MODIFIED_BY VARCHAR2(30 BYTE) NOT NULL 
, MODIFIED_DATE DATE NOT NULL 
, CONSTRAINT SECTION_PK PRIMARY KEY 
  (
    SECTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SECTION_PK ON SECTION (SECTION_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE SECTION
ADD CONSTRAINT SECTION_UK1 UNIQUE 
(
  COURSE_NO 
, SECTION_NO 
)
USING INDEX 
(
    CREATE UNIQUE INDEX SECTION_UK1 ON SECTION (COURSE_NO ASC, SECTION_NO ASC) 
    LOGGING 
    TABLESPACE USERS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

ALTER TABLE SECTION
ADD CONSTRAINT SECTION_FK1 FOREIGN KEY
(
  COURSE_NO 
)
REFERENCES COURSE
(
  COURSE_NO 
)
ENABLE;


CREATE TABLE STUDENT 
(
  STUDENT_ID NUMBER(8, 0) NOT NULL 
, SALUTATION VARCHAR2(5 BYTE) 
, FIRST_NAME VARCHAR2(25 BYTE) 
, LAST_NAME VARCHAR2(25 BYTE) NOT NULL 
, STREET_ADDRESS VARCHAR2(50 BYTE) 
, ZIP VARCHAR2(5 BYTE) NOT NULL 
, PHONE VARCHAR2(15 BYTE) 
, EMPLOYER VARCHAR2(50 BYTE) 
, REGISTRATION_DATE DATE NOT NULL 
, CREATED_BY VARCHAR2(30 BYTE) NOT NULL 
, CREATED_DATE DATE NOT NULL 
, MODIFIED_BY VARCHAR2(30 BYTE) NOT NULL 
, MODIFIED_DATE DATE NOT NULL 
, CONSTRAINT STUDENT_PK PRIMARY KEY 
  (
    STUDENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX STUDENT_PK ON STUDENT (STUDENT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
