ALTER TABLE ASP_NET_USERS
ADD CONSTRAINT ASP_NET_USERS_UK1 UNIQUE 
(
  USER_NAME 
)
ENABLE;

CREATE TABLE SCHOOL_USER 
(
  USER_NAME NVARCHAR2(256) NOT NULL 
, SCHOOL_ID NUMBER(8) NOT NULL 
, CONSTRAINT SCHOOL_USER_PK PRIMARY KEY 
  (
    USER_NAME 
  , SCHOOL_ID 
  )
  ENABLE 
);

ALTER TABLE SCHOOL_USER
ADD CONSTRAINT SCHOOL_USER_FK1 FOREIGN KEY
(
  USER_NAME 
)
REFERENCES ASP_NET_USERS
(
  USER_NAME 
)
ENABLE;

ALTER TABLE SCHOOL_USER
ADD CONSTRAINT SCHOOL_USER_FK2 FOREIGN KEY
(
  SCHOOL_ID 
)
REFERENCES SCHOOL
(
  SCHOOL_ID 
)
ENABLE;

INSERT INTO "C##_UD_TRUST"."SCHOOL" (SCHOOL_ID, SCHOOL_NAME) VALUES ('2', 'WILMU');
INSERT INTO "C##_UD_TRUST"."SCHOOL" (SCHOOL_ID, SCHOOL_NAME) VALUES ('3', 'DTCC');

INSERT INTO "C##_UD_TRUST"."ASP_NET_USERS" (ID, USER_NAME, EMAIL_CONFIRMED, PHONE_NUMBER_CONFIRMED, TWO_FACTOR_ENABLED, LOCKOUT_ENABLED, ACCESS_FAILED_COUNT) VALUES (N'1', N'USER1', '1', '1', '1', '0', '0');
INSERT INTO "C##_UD_TRUST"."ASP_NET_USERS" (ID, USER_NAME, EMAIL_CONFIRMED, PHONE_NUMBER_CONFIRMED, TWO_FACTOR_ENABLED, LOCKOUT_ENABLED, ACCESS_FAILED_COUNT) VALUES (N'2', N'USER2', '1', '1', '1', '0', '0');

INSERT INTO "C##_UD_TRUST"."SCHOOL_USER" (USER_NAME, SCHOOL_ID) VALUES (N'USER1', '1');
INSERT INTO "C##_UD_TRUST"."SCHOOL_USER" (USER_NAME, SCHOOL_ID) VALUES (N'USER2', '1');
INSERT INTO "C##_UD_TRUST"."SCHOOL_USER" (USER_NAME, SCHOOL_ID) VALUES (N'USER2', '2');
INSERT INTO "C##_UD_TRUST"."SCHOOL_USER" (USER_NAME, SCHOOL_ID) VALUES (N'USER2', '3');


Grant select,update,insert,delete on COURSE to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on SECTION to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ENROLLMENT to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on STUDENT to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on SCHOOL to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on SCHOOL_USER to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_USERS to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_USER_CLAIMS to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_USER_LOGINS to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_USER_TOKENS to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_ROLE_CLAIMS to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_ROLES to C##CISC437_STUDENT_ROLE;
Grant select,update,insert,delete on ASP_NET_USER_ROLES to C##CISC437_STUDENT_ROLE;